# Site settings
title: likeDew - Haijin's Blog
name: likeDew
email: 
description: Haijin的产品和生活思考
keywords: likedew,产品,硬件,吴海金,交互,移动互联网,APP,吴海金的博客,Haijin,Haijin‘s Blog,智能硬件

# permalink: /articles/:categories/:title/
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
url: http://likedew.com
baseurl:  "/"
domain: likedew.com
permalink:     /articles/:categories/:title/
paginate_path: 'page:num'
paginate:   10

# Build settings
future:      true
markdown: kramdown
highlighter: pygments
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: true
coderay:
  coderay_wrap: div
  coderay_line_numbers: nil
  coderay_tab_width: 4
  coderay_bold_every: 10
  coderay_css: class
excerpt_separator: "\n\n"

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap

disqus:
  id: likedew

google:
    analytics_id: UA-62566206-1

timezone:    PRC
encoding:    UTF-8

# navigation
navs:
  -
    href: /
    label: Home

#  -
#   href: http://www.zhihu.com/people/hyking
#   label: Zhihu
#   target: _blank

#  -
#   href: http://weibo.com/1783351805
#   label: Weibo
#   target: _blank

  -
    href: /about
    label: About

popular_repos: ['pinyin', 'wechat', 'writor', 'laravel-wechat', 'laravel-lang', 'laravel-pinyin', 'latest-laravel', 'latest-lumen']
contribute_repos: ['laravel/framework', 'tymondesigns/jwt-auth', 'caouecs/Laravel-lang']
